// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea6Empresa.DAL;

#nullable disable

namespace Tarea6Empresa.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220304145225_Migraciion_Inicial")]
    partial class Migraciion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Tarea6Empresa.Entidades.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamento");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Descripcion = "Financiero"
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Descripcion = "Recursos Humanos"
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Descripcion = "Compras"
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Descripcion = "Administrador"
                        });
                });

            modelBuilder.Entity("Tarea6Empresa.Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Salario")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaIngreso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Tarea6Empresa.Entidades.Nomina", b =>
                {
                    b.Property<int>("NominaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AFP")
                        .HasColumnType("REAL");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("HorasExtra")
                        .HasColumnType("REAL");

                    b.Property<double>("ISR")
                        .HasColumnType("REAL");

                    b.Property<double>("SFS")
                        .HasColumnType("REAL");

                    b.Property<double>("SalarioMensual")
                        .HasColumnType("REAL");

                    b.Property<double>("SueldoTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDecuentos")
                        .HasColumnType("REAL");

                    b.HasKey("NominaId");

                    b.ToTable("Nomina");
                });

            modelBuilder.Entity("Tarea6Empresa.Entidades.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RolId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Descripcion = "Gerente"
                        },
                        new
                        {
                            RolId = 2,
                            Descripcion = "Secreatrio"
                        },
                        new
                        {
                            RolId = 3,
                            Descripcion = "Contable"
                        },
                        new
                        {
                            RolId = 4,
                            Descripcion = "Desarrollador"
                        },
                        new
                        {
                            RolId = 5,
                            Descripcion = "Desarrollador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
